# Generated by Django 5.1.6 on 2025-02-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.CharField(default='1', max_length=1000),
            preserve_default=False,
        ),
    ]
